import Head from "next/head";
import Categories from "../src/components/homepage/categories/Categories";
import FeaturedProducts from "../src/components/homepage/featuredProducts/FeaturedProducts";
import Hero from "../src/components/homepage/Hero";

const featuredProducts = [
  {
    name: "zx9 speaker",
    path: "",
    imageSrc: "/assets/home/desktop/image-speaker-zx9.png",
    style: "primary",
  },
  {
    name: "zx7 speaker",
    path: "",
    imageSrc: "/assets/home/desktop/image-speaker-zx7.jpg",
    style: "secondary",
  },
  {
    name: "yx1 earphones",
    path: "",
    imageSrc: "/assets/home/desktop/image-earphones-yx1.jpg",
    style: "seperate",
  },
];

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flow">
        <Hero />
        <div className="container flow">
          <Categories />
          <FeaturedProducts featuredProducts={featuredProducts} />
        </div>
      </main>
    </>
  );
};

export default Home;
