import { GetStaticProps } from "next";
import Head from "next/head";

import { FC } from "react";

import Gallery from "../src/components/gallery/Gallery";
import { IItemShort } from "../src/types/IItemShort";

interface IProps {
  galleryItems: IItemShort[];
  status: string;
}

export const getStaticProps: GetStaticProps = async () => {
  let props: IProps = {
    galleryItems: [],
    status: "",
  };

  try {
    const res = await fetch("http://localhost:3001/api/gallery");
    const data = await res.json();
    props.galleryItems = data.galleryItems;
    props.status = "success";
  } catch (error) {
    props.status = "error";
    console.log(error);
  }
  return {
    props,
  };
};

const HomePage: FC<IProps> = ({ galleryItems, status }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery galleryItems={galleryItems} />
      </main>
    </>
  );
};

export default HomePage;
